# Generated by Django 6.0.3 on 2026-06-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_duration_alter_videoview_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='videoview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='videoreaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='videoview',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='videos.video'),
        ),
        migrations.AddConstraint(
            model_name='videoreaction',
            constraint=models.UniqueConstraint(fields=('user', 'video'), name='unique_user_video_reaction'),
        ),
    ]
