# Generated by Django 6.0.3 on 2026-06-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_options_alter_videoview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cloudinary_thumbnail_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='cloudinary_video_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
