# Generated by Django 6.0.3 on 2026-06-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_cloudinary_thumbnail_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cloudinary_thumbnail_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='cloudinary_video_id',
        ),
    ]
