# Generated by Django 6.0.3 on 2026-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestream", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamkey",
            name="key",
            field=models.CharField(
                default="4e0e0c4bea5841e68e07f9766675d854",
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
