# Generated by Django 6.0.3 on 2026-07-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livestream", "0002_alter_streamkey_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamkey",
            name="key",
            field=models.CharField(
                default="1567f587991241acb58169e47e7d9ef4",
                editable=False,
                max_length=64,
                unique=True,
            ),
        ),
    ]
