# Generated by Django 6.0.3 on 2026-06-29 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('videos', '0004_alter_video_options_alter_videoview_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinterest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='videotagmap',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userinterest',
            constraint=models.UniqueConstraint(fields=('user', 'tag'), name='unique_user_tag_interest'),
        ),
        migrations.AddConstraint(
            model_name='videotagmap',
            constraint=models.UniqueConstraint(fields=('video', 'tag'), name='unique_video_tag'),
        ),
    ]
